import { Injectable } from '@nestjs/common';
import { AccountTxnType, BuyerType } from '@prisma/client';
import ExcelJS from 'exceljs';
import { PrismaService } from '../prisma/prisma.service';
import { CashierService } from './cashier.service';

type FinancialReportData = Awaited<
  ReturnType<CashierService['getFinancialReport']>
>;
type BalanceSheetData = Awaited<ReturnType<CashierService['getBalanceSheet']>>;

type ShuMemberRow = {
  employeeId: string;
  employeeCode: string;
  name: string;
  simpanan: number;
  transaksi: number;
  jasaModal: number;
  jasaUsaha: number;
  shuDiterima: number;
};

@Injectable()
export class CashierReportExportService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly cashierService: CashierService,
  ) {}

  private readonly currencyFormat = '"Rp" #,##0;[Red]-"Rp" #,##0';
  private readonly blueFill = {
    type: 'pattern' as const,
    pattern: 'solid' as const,
    fgColor: { argb: 'FF3B82F6' },
  };
  private readonly grayFill = {
    type: 'pattern' as const,
    pattern: 'solid' as const,
    fgColor: { argb: 'FFF3F4F6' },
  };
  private readonly border = {
    top: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
    left: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
    bottom: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
    right: { style: 'thin' as const, color: { argb: 'FFD1D5DB' } },
  };

  private startOfDay(d: Date): Date {
    const x = new Date(d);
    x.setHours(0, 0, 0, 0);
    return x;
  }

  private endExclusiveDay(d: Date): Date {
    const x = this.startOfDay(d);
    x.setDate(x.getDate() + 1);
    return x;
  }

  private formatDate(d: Date): string {
    return d.toLocaleDateString('id-ID', {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
      timeZone: 'Asia/Jakarta',
    });
  }

  private formatPeriodLabel(from: Date, to: Date): string {
    return `${from.toLocaleDateString('id-ID', {
      month: 'long',
      year: 'numeric',
      timeZone: 'Asia/Jakarta',
    })} - ${to.toLocaleDateString('id-ID', {
      month: 'long',
      year: 'numeric',
      timeZone: 'Asia/Jakarta',
    })}`;
  }

  private safeFileDate(value: Date): string {
    return new Intl.DateTimeFormat('sv-SE', {
      timeZone: 'Asia/Jakarta',
    }).format(value);
  }

  private setPrintLayout(ws: ExcelJS.Worksheet) {
    ws.pageSetup = {
      orientation: 'landscape',
      fitToPage: true,
      fitToWidth: 1,
      fitToHeight: 0,
      paperSize: 9,
      margins: {
        left: 0.7,
        right: 0.7,
        top: 0.75,
        bottom: 0.75,
        header: 0.3,
        footer: 0.3,
      },
    };
    ws.headerFooter.oddFooter = '&LGenerated by System&RPage &P of &N';
  }

  private applyReportHeader(
    ws: ExcelJS.Worksheet,
    systemName: string,
    title: string,
    periodLabel: string,
    exportDate: string,
    lastColumn: string,
  ) {
    ws.mergeCells(`A1:${lastColumn}1`);
    ws.mergeCells(`A2:${lastColumn}2`);
    ws.mergeCells(`A3:${lastColumn}3`);
    ws.mergeCells(`A4:${lastColumn}4`);

    ws.getCell('A1').value = systemName;
    ws.getCell('A2').value = title;
    ws.getCell('A3').value = `Periode: ${periodLabel}`;
    ws.getCell('A4').value = `Tanggal Export: ${exportDate}`;

    for (const addr of ['A1', 'A2', 'A3', 'A4']) {
      const cell = ws.getCell(addr);
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
      cell.font = {
        bold: true,
        size: addr === 'A1' ? 16 : addr === 'A2' ? 15 : 12,
        color: { argb: addr === 'A1' || addr === 'A2' ? 'FF111827' : 'FF374151' },
      };
    }
  }

  private styleTableHeader(row: ExcelJS.Row) {
    row.eachCell((cell) => {
      cell.fill = this.blueFill;
      cell.font = { bold: true, color: { argb: 'FFFFFFFF' } };
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
      cell.border = this.border;
    });
  }

  private styleBodyRow(
    row: ExcelJS.Row,
    opts?: {
      zebra?: boolean;
      rightAlignFromColumn?: number;
      bold?: boolean;
    },
  ) {
    row.eachCell((cell, colNumber) => {
      cell.border = this.border;
      cell.alignment = {
        vertical: 'middle',
        horizontal:
          opts?.rightAlignFromColumn && colNumber >= opts.rightAlignFromColumn
            ? 'right'
            : 'left',
      };
      if (opts?.bold) cell.font = { bold: true };
      if (opts?.zebra) cell.fill = this.grayFill;
    });
  }

  private applyCurrencyToColumns(
    ws: ExcelJS.Worksheet,
    columns: string[],
    fromRow: number,
    toRow: number,
  ) {
    for (const col of columns) {
      for (let row = fromRow; row <= toRow; row += 1) {
        ws.getCell(`${col}${row}`).numFmt = this.currencyFormat;
      }
    }
  }

  private autoSizeColumns(ws: ExcelJS.Worksheet) {
    ws.columns.forEach((column) => {
      let max = 12;
      column.eachCell?.({ includeEmpty: true }, (cell) => {
        const raw = cell.value;
        const value =
          raw === null || raw === undefined
            ? ''
            : typeof raw === 'object' && 'richText' in raw
              ? raw.richText.map((x) => x.text).join('')
              : String(raw);
        max = Math.max(max, value.length + 2);
      });
      column.width = Math.min(max, 28);
    });
  }

  private allocateByWeight(
    total: number,
    rows: { employeeId: string; weight: number }[],
  ): Map<string, number> {
    const result = new Map<string, number>();
    const positive = rows.filter((row) => row.weight > 0);
    const totalWeight = positive.reduce((sum, row) => sum + row.weight, 0);
    if (total <= 0 || totalWeight <= 0) {
      for (const row of rows) result.set(row.employeeId, 0);
      return result;
    }

    const withRemainders = positive.map((row) => {
      const exact = (total * row.weight) / totalWeight;
      const base = Math.floor(exact);
      return {
        employeeId: row.employeeId,
        base,
        remainder: exact - base,
      };
    });
    let allocated = withRemainders.reduce((sum, row) => sum + row.base, 0);
    let remaining = total - allocated;
    withRemainders.sort((a, b) => b.remainder - a.remainder);
    for (let i = 0; i < withRemainders.length && remaining > 0; i += 1) {
      withRemainders[i].base += 1;
      remaining -= 1;
    }
    for (const row of rows) result.set(row.employeeId, 0);
    for (const row of withRemainders) result.set(row.employeeId, row.base);
    return result;
  }

  private sanitizeSheetName(name: string) {
    return name.slice(0, 31);
  }

  private async getShuDataset(from: Date, to: Date) {
    const start = this.startOfDay(from);
    const endExclusive = this.endExclusiveDay(to);
    const [financial, rawSales, walletCredits] = await Promise.all([
      this.cashierService.getFinancialReport(from, to),
      this.prisma.sale.findMany({
        where: {
          buyerType: BuyerType.EMPLOYEE,
          createdAt: { gte: start, lt: endExclusive },
          employee: { employeeCode: { not: 'GENERAL' } },
        },
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          createdAt: true,
          total: true,
          cashPaid: true,
          paidByMandatory: true,
          addedDebt: true,
          employeeId: true,
          employee: {
            select: {
              employeeCode: true,
              name: true,
            },
          },
        },
      }),
      this.prisma.accountTxn.groupBy({
        by: ['employeeId'],
        where: {
          type: AccountTxnType.WALLET_CREDIT,
          createdAt: { gte: start, lt: endExclusive },
          employee: { employeeCode: { not: 'GENERAL' } },
        },
        _sum: { amount: true },
      }),
    ]);

    const salesByEmployee = new Map<
      string,
      { transaksi: number; employeeCode: string; name: string }
    >();
    for (const sale of rawSales) {
      if (!sale.employeeId || !sale.employee) continue;
      const prev = salesByEmployee.get(sale.employeeId) ?? {
        transaksi: 0,
        employeeCode: sale.employee.employeeCode,
        name: sale.employee.name,
      };
      prev.transaksi += sale.total;
      salesByEmployee.set(sale.employeeId, prev);
    }

    const walletByEmployee = new Map(
      walletCredits.map((row) => [row.employeeId, row._sum.amount ?? 0]),
    );
    const employeeIds = [...new Set([...salesByEmployee.keys(), ...walletByEmployee.keys()])];

    const employees = await this.prisma.employee.findMany({
      where: {
        id: { in: employeeIds },
        employeeCode: { not: 'GENERAL' },
      },
      orderBy: { name: 'asc' },
      select: {
        id: true,
        employeeCode: true,
        name: true,
      },
    });

    const totalPendapatan = financial.sales.totalSales;
    const totalBiaya = 0;
    const shuKotor = Math.max(0, totalPendapatan - totalBiaya);
    const cadangan = Math.trunc(shuKotor * 0.2);
    const shuDibagikan = shuKotor - cadangan;
    const jasaModalTotal = Math.trunc(shuDibagikan * 0.4);
    const jasaUsahaTotal = shuDibagikan - jasaModalTotal;

    const baseRows = employees.map((employee) => ({
      employeeId: employee.id,
      employeeCode: employee.employeeCode,
      name: employee.name,
      simpanan: walletByEmployee.get(employee.id) ?? 0,
      transaksi: salesByEmployee.get(employee.id)?.transaksi ?? 0,
    }));

    const jasaModalMap = this.allocateByWeight(
      jasaModalTotal,
      baseRows.map((row) => ({ employeeId: row.employeeId, weight: row.simpanan })),
    );
    const jasaUsahaMap = this.allocateByWeight(
      jasaUsahaTotal,
      baseRows.map((row) => ({ employeeId: row.employeeId, weight: row.transaksi })),
    );

    const memberRows: ShuMemberRow[] =
      baseRows.length > 0
        ? baseRows.map((row) => {
            const jasaModal = jasaModalMap.get(row.employeeId) ?? 0;
            const jasaUsaha = jasaUsahaMap.get(row.employeeId) ?? 0;
            return {
              ...row,
              jasaModal,
              jasaUsaha,
              shuDiterima: jasaModal + jasaUsaha,
            };
          })
        : [
            {
              employeeId: 'placeholder',
              employeeCode: '-',
              name: 'Belum ada data anggota pada periode ini',
              simpanan: 0,
              transaksi: 0,
              jasaModal: 0,
              jasaUsaha: 0,
              shuDiterima: 0,
            },
          ];

    return {
      financial,
      start,
      endExclusive,
      summary: {
        totalPendapatan,
        totalBiaya,
        shuKotor,
        cadangan,
        jasaModal: jasaModalTotal,
        jasaUsaha: jasaUsahaTotal,
        shuDibagikan,
      },
      memberRows,
      rawSales,
      assumptions: [
        'Total biaya saat ini diasumsikan 0 karena modul biaya operasional belum dimodelkan di ledger.',
        'Simpanan anggota dihitung dari total transaksi WALLET_CREDIT pada periode laporan.',
        'Pembagian SHU: 20% cadangan, lalu sisa dibagi 40% jasa modal dan 60% jasa usaha.',
      ],
    };
  }

  async buildFinancialWorkbook(from: Date, to: Date) {
    const [financial, balance, sales] = await Promise.all([
      this.cashierService.getFinancialReport(from, to),
      this.cashierService.getBalanceSheet(to),
      this.prisma.sale.findMany({
        where: {
          createdAt: {
            gte: this.startOfDay(from),
            lt: this.endExclusiveDay(to),
          },
        },
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          createdAt: true,
          buyerType: true,
          total: true,
          cashPaid: true,
          paidByMandatory: true,
          addedDebt: true,
          employee: {
            select: {
              employeeCode: true,
              name: true,
            },
          },
        },
      }),
    ]);

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Waserda';
    workbook.created = new Date();
    workbook.modified = new Date();

    const periodLabel = this.formatPeriodLabel(from, to);
    const exportDate = this.formatDate(new Date());

    const summarySheet = workbook.addWorksheet('Laporan Keuangan');
    this.setPrintLayout(summarySheet);
    this.applyReportHeader(
      summarySheet,
      'Waserda',
      'Laporan Keuangan',
      periodLabel,
      exportDate,
      'E',
    );
    summarySheet.addRow([]);
    const summaryStart = 6;
    summarySheet.getCell(`A${summaryStart}`).value = 'Keterangan';
    summarySheet.getCell(`B${summaryStart}`).value = 'Nilai';
    this.styleTableHeader(summarySheet.getRow(summaryStart));

    const financialRows: Array<{
      label: string;
      value: number;
      currency: boolean;
      bold?: boolean;
    }> = [
      {
        label: 'Total Penjualan',
        value: financial.sales.totalSales,
        currency: true,
      },
      {
        label: 'Jumlah Transaksi',
        value: financial.sales.transactionCount,
        currency: false,
      },
      {
        label: 'Penjualan Pegawai',
        value: financial.sales.employeeSales,
        currency: true,
      },
      {
        label: 'Penjualan Umum',
        value: financial.sales.generalSales,
        currency: true,
      },
      {
        label: 'Cash dari Penjualan',
        value: financial.movements.cashFromSales,
        currency: true,
      },
      {
        label: 'Saldo Wajib Terpakai',
        value: financial.movements.walletUsed,
        currency: true,
      },
      {
        label: 'Hutang Baru dari Penjualan',
        value: financial.movements.debtAddedFromSales,
        currency: true,
      },
      {
        label: 'Pembayaran Hutang',
        value: financial.movements.debtPayment,
        currency: true,
      },
      {
        label: 'Topup Saldo Wajib',
        value: financial.movements.walletTopupCredit,
        currency: true,
      },
      {
        label: 'Estimasi Total Cash In',
        value: financial.cashflowEstimate.totalCashIn,
        currency: true,
        bold: true,
      },
    ];
    financialRows.forEach((item, index) => {
      const row = summarySheet.getRow(summaryStart + 1 + index);
      row.getCell(1).value = item.label;
      row.getCell(2).value = item.value;
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 2,
        bold: item.bold,
      });
      if (item.currency) {
        row.getCell(2).numFmt = this.currencyFormat;
      }
    });
    summarySheet.views = [{ state: 'frozen', ySplit: summaryStart }];
    this.autoSizeColumns(summarySheet);

    const balanceSheet = workbook.addWorksheet('Neraca');
    this.setPrintLayout(balanceSheet);
    this.applyReportHeader(
      balanceSheet,
      'Waserda',
      'Laporan Neraca',
      periodLabel,
      exportDate,
      'E',
    );
    const balanceHeaderRow = 6;
    balanceSheet.getRow(balanceHeaderRow).values = ['Komponen', 'Nilai'];
    this.styleTableHeader(balanceSheet.getRow(balanceHeaderRow));
    const balanceRows = [
      ['Kas (estimasi)', balance.assets.cashEstimate],
      ['Persediaan', balance.assets.inventoryValue],
      ['Piutang Pegawai', balance.assets.receivableEmployeeDebt],
      ['Total Aset', balance.assets.total],
      ['Kewajiban Saldo Wajib', balance.liabilities.mandatoryWalletLiability],
      ['Total Liabilitas', balance.liabilities.total],
      ['Ekuitas', balance.equity.total],
    ];
    balanceRows.forEach(([label, value], index) => {
      const row = balanceSheet.getRow(balanceHeaderRow + 1 + index);
      row.values = [label, value];
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 2,
        bold:
          label === 'Total Aset' ||
          label === 'Total Liabilitas' ||
          label === 'Ekuitas',
      });
      row.getCell(2).numFmt = this.currencyFormat;
    });
    const notesStart = balanceHeaderRow + balanceRows.length + 3;
    balanceSheet.getCell(`A${notesStart}`).value = 'Catatan';
    balanceSheet.getCell(`A${notesStart}`).font = { bold: true };
    balance.notes.forEach((note, index) => {
      balanceSheet.mergeCells(`A${notesStart + 1 + index}:E${notesStart + 1 + index}`);
      balanceSheet.getCell(`A${notesStart + 1 + index}`).value = `- ${note}`;
      balanceSheet.getCell(`A${notesStart + 1 + index}`).alignment = {
        wrapText: true,
      };
    });
    balanceSheet.views = [{ state: 'frozen', ySplit: balanceHeaderRow }];
    this.autoSizeColumns(balanceSheet);

    const salesSheet = workbook.addWorksheet('Rekap Transaksi');
    this.setPrintLayout(salesSheet);
    this.applyReportHeader(
      salesSheet,
      'Waserda',
      'Rekap Transaksi Penjualan',
      periodLabel,
      exportDate,
      'I',
    );
    const salesHeaderRow = 6;
    salesSheet.getRow(salesHeaderRow).values = [
      'No',
      'Tanggal',
      'Sale ID',
      'Pembeli',
      'Tipe',
      'Cash',
      'Saldo Wajib',
      'Hutang Baru',
      'Total',
    ];
    this.styleTableHeader(salesSheet.getRow(salesHeaderRow));
    const salesRows =
      sales.length > 0
        ? sales
        : [
            {
              id: '-',
              createdAt: new Date(),
              buyerType: BuyerType.GENERAL,
              total: 0,
              cashPaid: 0,
              paidByMandatory: 0,
              addedDebt: 0,
              employee: null,
            },
          ];
    salesRows.forEach((sale, index) => {
      const row = salesSheet.getRow(salesHeaderRow + 1 + index);
      row.values = [
        index + 1,
        this.formatDate(new Date(sale.createdAt)),
        sale.id,
        sale.employee?.name ?? 'Pembeli Umum',
        sale.buyerType,
        sale.cashPaid,
        sale.paidByMandatory,
        sale.addedDebt,
        sale.total,
      ];
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 6,
      });
    });
    this.applyCurrencyToColumns(
      salesSheet,
      ['F', 'G', 'H', 'I'],
      salesHeaderRow + 1,
      salesHeaderRow + salesRows.length,
    );
    salesSheet.views = [{ state: 'frozen', ySplit: salesHeaderRow }];
    this.autoSizeColumns(salesSheet);

    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    const fileName = `laporan-keuangan-${this.safeFileDate(from)}_sd_${this.safeFileDate(to)}.xlsx`;
    return { buffer, fileName };
  }

  async buildShuWorkbook(from: Date, to: Date) {
    const dataset = await this.getShuDataset(from, to);
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Waserda';
    workbook.created = new Date();
    workbook.modified = new Date();

    const periodLabel = this.formatPeriodLabel(from, to);
    const exportDate = this.formatDate(new Date());

    const shuSheet = workbook.addWorksheet(this.sanitizeSheetName('Laporan SHU'));
    this.setPrintLayout(shuSheet);
    this.applyReportHeader(
      shuSheet,
      'Waserda',
      'Laporan Sisa Hasil Usaha (SHU)',
      periodLabel,
      exportDate,
      'E',
    );

    const summaryHeaderRow = 6;
    shuSheet.getRow(summaryHeaderRow).values = ['Keterangan', 'Nominal (Rp)'];
    this.styleTableHeader(shuSheet.getRow(summaryHeaderRow));
    const summaryRows = [
      ['Total Pendapatan', dataset.summary.totalPendapatan],
      ['Total Biaya', dataset.summary.totalBiaya],
      ['SHU Kotor', dataset.summary.shuKotor],
      ['Cadangan', dataset.summary.cadangan],
      ['Jasa Modal', dataset.summary.jasaModal],
      ['Jasa Usaha', dataset.summary.jasaUsaha],
      ['SHU Dibagikan', dataset.summary.shuDibagikan],
    ];
    summaryRows.forEach(([label, value], index) => {
      const row = shuSheet.getRow(summaryHeaderRow + 1 + index);
      row.values = [label, value];
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 2,
        bold: label === 'SHU Kotor' || label === 'SHU Dibagikan',
      });
    });
    this.applyCurrencyToColumns(
      shuSheet,
      ['B'],
      summaryHeaderRow + 1,
      summaryHeaderRow + summaryRows.length,
    );

    const notesRow = summaryHeaderRow + summaryRows.length + 2;
    shuSheet.getCell(`A${notesRow}`).value = 'Dasar Perhitungan';
    shuSheet.getCell(`A${notesRow}`).font = { bold: true };
    dataset.assumptions.forEach((note, index) => {
      shuSheet.mergeCells(`A${notesRow + 1 + index}:E${notesRow + 1 + index}`);
      shuSheet.getCell(`A${notesRow + 1 + index}`).value = `- ${note}`;
      shuSheet.getCell(`A${notesRow + 1 + index}`).alignment = { wrapText: true };
    });

    const membersHeaderRow = notesRow + dataset.assumptions.length + 3;
    shuSheet.getRow(membersHeaderRow).values = [
      'No',
      'Nama Anggota',
      'Simpanan',
      'Transaksi',
      'SHU Diterima',
    ];
    this.styleTableHeader(shuSheet.getRow(membersHeaderRow));
    dataset.memberRows.forEach((member, index) => {
      const row = shuSheet.getRow(membersHeaderRow + 1 + index);
      row.values = [
        index + 1,
        member.name,
        member.simpanan,
        member.transaksi,
        member.shuDiterima,
      ];
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 3,
      });
    });
    const totalRowIndex = membersHeaderRow + dataset.memberRows.length + 1;
    const totalRow = shuSheet.getRow(totalRowIndex);
    totalRow.values = ['', 'Total SHU Dibagikan', '', '', dataset.memberRows.reduce((sum, row) => sum + row.shuDiterima, 0)];
    this.styleBodyRow(totalRow, { rightAlignFromColumn: 5, bold: true });
    this.applyCurrencyToColumns(
      shuSheet,
      ['C', 'D', 'E'],
      membersHeaderRow + 1,
      totalRowIndex,
    );
    shuSheet.views = [{ state: 'frozen', ySplit: membersHeaderRow }];
    this.autoSizeColumns(shuSheet);

    const detailSheet = workbook.addWorksheet(this.sanitizeSheetName('Detail Anggota'));
    this.setPrintLayout(detailSheet);
    this.applyReportHeader(
      detailSheet,
      'Waserda',
      'Detail Pembagian SHU Anggota',
      periodLabel,
      exportDate,
      'H',
    );
    const detailHeaderRow = 6;
    detailSheet.getRow(detailHeaderRow).values = [
      'No',
      'Kode Anggota',
      'Nama Anggota',
      'Simpanan',
      'Transaksi',
      'Jasa Modal',
      'Jasa Usaha',
      'SHU Diterima',
    ];
    this.styleTableHeader(detailSheet.getRow(detailHeaderRow));
    dataset.memberRows.forEach((member, index) => {
      const row = detailSheet.getRow(detailHeaderRow + 1 + index);
      row.values = [
        index + 1,
        member.employeeCode,
        member.name,
        member.simpanan,
        member.transaksi,
        member.jasaModal,
        member.jasaUsaha,
        member.shuDiterima,
      ];
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 4,
      });
    });
    this.applyCurrencyToColumns(
      detailSheet,
      ['D', 'E', 'F', 'G', 'H'],
      detailHeaderRow + 1,
      detailHeaderRow + dataset.memberRows.length,
    );
    detailSheet.views = [{ state: 'frozen', ySplit: detailHeaderRow }];
    this.autoSizeColumns(detailSheet);

    const txSheet = workbook.addWorksheet(this.sanitizeSheetName('Rekap Transaksi'));
    this.setPrintLayout(txSheet);
    this.applyReportHeader(
      txSheet,
      'Waserda',
      'Rekap Transaksi Anggota',
      periodLabel,
      exportDate,
      'I',
    );
    const txHeaderRow = 6;
    txSheet.getRow(txHeaderRow).values = [
      'No',
      'Tanggal',
      'Sale ID',
      'Kode Anggota',
      'Nama Anggota',
      'Cash',
      'Saldo Wajib',
      'Hutang Baru',
      'Total',
    ];
    this.styleTableHeader(txSheet.getRow(txHeaderRow));
    const rawSales =
      dataset.rawSales.length > 0
        ? dataset.rawSales
        : [
            {
              id: '-',
              createdAt: new Date(),
              total: 0,
              cashPaid: 0,
              paidByMandatory: 0,
              addedDebt: 0,
              employeeId: null,
              employee: null,
            },
          ];
    rawSales.forEach((sale, index) => {
      const row = txSheet.getRow(txHeaderRow + 1 + index);
      row.values = [
        index + 1,
        this.formatDate(new Date(sale.createdAt)),
        sale.id,
        sale.employee?.employeeCode ?? '-',
        sale.employee?.name ?? '-',
        sale.cashPaid,
        sale.paidByMandatory,
        sale.addedDebt,
        sale.total,
      ];
      this.styleBodyRow(row, {
        zebra: index % 2 === 1,
        rightAlignFromColumn: 6,
      });
    });
    this.applyCurrencyToColumns(
      txSheet,
      ['F', 'G', 'H', 'I'],
      txHeaderRow + 1,
      txHeaderRow + rawSales.length,
    );
    txSheet.views = [{ state: 'frozen', ySplit: txHeaderRow }];
    this.autoSizeColumns(txSheet);

    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
    const fileName = `laporan-shu-${this.safeFileDate(from)}_sd_${this.safeFileDate(to)}.xlsx`;
    return { buffer, fileName };
  }
}
